#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Initialize variables to store the sums
    min_sum = 0
    max_sum = 0
    len_array = len(arr)
    a = arr.sort() # This will sort the list in place in ascending order

# Loop through the first 4 elements (indices 0 to 3) to calculate the sums
    for i in range(len_array - 1):
        min_sum += arr[i]
        max_sum += arr[i+1]
    print (min_sum, max_sum)
    
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
